[project]
name = "pipen-dry"
dynamic = ["version"]
description = "Dry runner for pipen pipelines"
authors = [{name = "pwwang", email = "pwwang@pwwang.com"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.9,<4"
dependencies = ["pipen>=1.1"]

[tool.hatch.version]
path = "pipen_dry.py"

[project.optional-dependencies]
examples = ["google-cloud-storage>=3", "python-dotenv>=1"]

[project.entry-points.pipen_sched]
dry = "pipen_dry:PipenDryScheduler"

[project.entry-points.pipen]
dry = "pipen_dry:PipenDry"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 79
target-version = ['py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'

[tool.uv]
prerelease = "allow"
