name: Build and Deploy

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v6
      - name: Setup uv # Set Python version
        uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --all-groups --all-extras --upgrade
      - name: Run flake8
        run: uvx flake8 pipen_dry.py

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v6
      - name: Setup uv # Set Python version
        uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Publish to PyPI
        run: |
          uv build
          uv publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PASSWORD }}
        if: success()
